FROM golang:1.16

ADD . /functions-framework-go
WORKDIR /functions-framework-go

ENV GOPROXY="https://goproxy.cn"

EXPOSE 12345

ENTRYPOINT ["go"]

CMD ["run", "plugin/skywalking/test/sync-request/provider/provider.go"]