name: PluginsTest

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Plugin-SkyWalking:
    name: Plugin With Apache SkyWalking - ${{matrix.case.name}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        case:
          - name: Sync Request
            e2e: "plugin/skywalking/test/sync-request/e2e.yaml"
            env: compose
          - name: Binding Event
            e2e: "plugin/skywalking/test/binding-event/e2e.yaml"
            env: kind
          - name: Topic Event
            e2e: "plugin/skywalking/test/topic-event/e2e.yaml"
            env: kind
    steps:
      - uses: actions/checkout@v2
      - uses: apache/skywalking-infra-e2e@main
        with:
          e2e-file: ${{matrix.case.e2e}}
      - name: Show Container Logs
        if: ${{ failure() }} && matrix.case.e2e == 'compose'
        run: docker ps -a | grep -v CONTAINER | awk '{print $1}' | xargs -i docker logs {}
      - name: Cleanup
        if: ${{ failure() }}
        run: e2e cleanup -c ${{matrix.case.e2e}}